Updated pattern to new template
UKHomeOffice/design-system pull request #175
Opened 2020-09-01 13:48 UTC by joeedhorton

Updated pattern to new template: _Add multiple things_

2020-09-03 09:26 UTC, joeedhorton reviewed
This all looks good 👍

2020-09-03 13:45 UTC, karypun requested changes

2020-09-03 15:32 UTC, joeedhorton reviewed
I have made the changes whilst merging any new updates from the master into this branch so should be all good to go 👍

2020-09-14 19:24 UTC, karypun approved these changes

2020-09-14 19:24 UTC, merged