Cookie consent solution added to styles page
UKHomeOffice/design-system pull request #176
Opened 2020-09-03 15:19 UTC by joeedhorton

### Two decisions have been made. 

- **to have the link re-directed the github issue itself rather than the specific GitHub repo with specific guidance.** This is because we shouldn't assume witch GitHub repo they need (wordpress, nodejs, salesforce etc.)
- **to have the link open in a new tab**. We don't want them to be taken away from the design system if they find a problem or didn't find what they were looking for.

2020-09-04 08:05 UTC, MarionDownie commented
Hi Joe, see the guidance on this in the GOV.UK Design System - https://design-system.service.gov.uk/styles/typography/#links We should avoid opening links in a new tab for accessibility reasons.

2020-09-04 08:32 UTC, joeedhorton commented
All done 👍 removed the `target="blank"`

2020-09-04 09:41 UTC, zuzak commented on app/views/styles/index.html
> +                  documentation written by the cabinet office.
```suggestion
                  documentation written by the Cabinet Office.
```

2020-09-04 09:58 UTC, joeedhorton commented on app/views/styles/index.html
> +                  documentation written by the cabinet office.
Good spot @zuzak 👍

2020-09-04 12:58 UTC, MarionDownie commented
Had a look at this in the browser and looks fine, but I feel like it's too prominent - can the banner go at the bottom, below the main content for the styles? It is secondary to the main aim of the page, which is to find out which styling to use where.

2020-09-06 14:29 UTC, karypun requested changes
Could we amend "marketing and informational site" content as that is only one specific criteria making up the independent branding style. The cookie guidance applies to the other criteria listed too.  Could say something like, "For independently branded sites such as public-facing services not residing on GOV.UK, you must refer to the documentation written by the Cabinet Office." This should cover the criteria listed.

2020-09-07 05:53 UTC, MarionDownie commented
> Could we amend "marketing and informational site" content as that is only one specific criteria making up the independent branding style. The cookie guidance applies to the other criteria listed too. Could say something like, "For independently branded sites such as public-facing services not residing on GOV.UK, you must refer to the documentation written by the Cabinet Office." This should cover the criteria listed.

This sounds ok, though can we just remove the word 'residing'? Ta

2020-09-07 12:14 UTC, karypun approved these changes

2020-09-07 12:14 UTC, merged