changes made to variation links
UKHomeOffice/design-system pull request #189
Opened 2020-09-24 07:49 UTC by joeedhorton

2020-09-24 15:02 UTC, MarionDownie requested changes
Can you please add the extra word on this page, as the links don't make sense on their own. So, 

Confirmation: 
- with account created etc

2020-09-24 16:51 UTC, karypun approved these changes

2020-09-25 16:03 UTC, SueSpevack approved these changes

2020-09-25 16:05 UTC, SueSpevack approved these changes

2020-09-26 09:55 UTC, joeedhorton reviewed
All done

2020-09-28 06:23 UTC, MarionDownie approved these changes

2020-09-28 13:06 UTC, merged