Headings page and updates to sidebar nav
UKHomeOffice/design-system pull request #286
Opened 2021-07-19 10:46 UTC by ildrinn

Created a new Accessibility Headings page, and updated the sidebar nav to include this

2021-07-27 14:31 UTC, MarionDownie requested changes
Hi Susi, sorry for the delay. Can you please just a few small changes:

- typo in table, rouge 'C'- 'CStruggles with pages that have dense, unstructured or a lot of text'
- is it possible to remove the bullets before the staggered headings? Would look neater
- check spacing - some of the headings are very close to the text above. Perhaps just add in paragraph tags/breaks
- screenreader is shown as two words in the penultimate para - can you please make this one word, as elsewhere?
- link at the end is broken

2021-07-28 08:32 UTC, ildrinn commented
Hi Marion - I think I've done this now? (made the changes and pushed the updated file). Still learning GitHub so let me know if I've missed anything.

2021-07-28 15:28 UTC, RobinKnipe requested changes
Just a couple of minor amendments.

2021-07-28 16:32 UTC, daniel-ac-martin commented on apps/docs/src/common/pages/accessibility/headings.tsx
> +<p>Similarly, if part of your content works as a heading (for example, to head up content blocks in the footer, or in a sidebar list of related links) then you must use the correct html code as well
Should be fixed.

2021-07-28 16:32 UTC, daniel-ac-martin commented on apps/docs/src/common/pages/accessibility/headings.tsx
> +<p>Never skip heading levels – if you need a heading to look different, do this with css styles rather than with the html code. </p>
Should be fixed.

2021-07-28 16:33 UTC, daniel-ac-martin commented
@MarionDownie, @RobinKnipe: Ready to merge?

2021-07-30 13:39 UTC, MarionDownie commented
> Hi Marion - I think I've done this now? (made the changes and pushed the updated file). Still learning GitHub so let me know if I've missed anything.

Hi Susi, sorry for the delay - I've been scratching my head as to why I can't see your changes, but Daniel says they haven't been pushed. Can you please check and try again? Guess you may need to pull the latest from master.

2021-07-30 13:58 UTC, daniel-ac-martin requested changes

2021-07-30 13:58 UTC, daniel-ac-martin commented on apps/docs/src/common/pages/accessibility/headings.tsx
> +          <ul class="govuk-list">
These all need to be `className=` rather than `class=`.

2021-07-30 14:43 UTC, MarionDownie reviewed
Looks good - just two small things. 

Is it possible to keep the style of the nested headings Susi had previously without the bullets? I think the indents were useful to convey the structure visually (but it's better with nothing than with the extra bullets)

Could you add an extra space underneath the image and before the heading 'Structure is separate from appearance'?

2021-08-02 10:35 UTC, daniel-ac-martin commented
@haggishunt56: Would you mind making the two small amendments that Marion asked for above?

2021-08-02 10:36 UTC, daniel-ac-martin commented
With the 'nested headings', I think she wants something like:
```
<h1>
  <h2>
    <h3>
      <h4>
```

2021-08-02 13:59 UTC, haggishunt56 commented
> With the 'nested headings', I think she wants something like:
> 
> ```
> <h1>
>   <h2>
>     <h3>
>       <h4>
> ```

I've made this change, but think it would make more sense to the reader to close each tag too (and possibly include tags all the way up to `<h6>`). What do you think @daniel-ac-martin & @MarionDownie?

2021-08-02 14:40 UTC, daniel-ac-martin commented
@haggishunt56: Let's go with this for now.
We can always make further enhancements later.

2021-08-02 14:41 UTC, merged