445 status message multiple lines of text
UKHomeOffice/design-system pull request #469
Opened 2022-11-23 12:44 UTC by MikeDThorpe

- implements Tom's refactoring suggestion to ensure text is aligned correctly on tablet < screen sizes

2022-11-23 13:18 UTC, tomyems commented
Ah looks good thanks :) - I noticed that the spacing has changed on the other stories (which is a consequence of the changes I requested). Personally, I'm happy with making a breaking change, though we might need to amend the original stories from ` - due for review 31 May 2021` to `Due for review 31 May 2021`?

Probably one to show both to the design system working group

2022-11-24 11:34 UTC, MikeDThorpe commented
@tomyems - where has spacing changed in the other stories? I noticed on smaller screens the Status Message with no 'extra content' and no 'actions' (a.k.a buttons) had uneven margin caused by the status text styling. So i moved the styling from the status text to the 'extra content' text so this would only be applied if the extra text was present. Perhaps i haven't applied the new styling correctly if it looks off - i so i can fix this if it's an issue.

2022-11-25 09:17 UTC, tomyems commented
Looks good to me. It was about the spacing between the bold text and the '-'. Would be good to share in the design system working group to get their thoughts :)

2022-11-25 09:18 UTC, tomyems approved these changes
LGTM - does the version number need changing

2022-11-25 10:43 UTC, MikeDThorpe commented
> LGTM - does the version number need changing

Where can i find the version number? And what should this be incremented too?

2022-11-28 17:24 UTC, tomyems commented
> > LGTM - does the version number need changing
> 
> Where can i find the version number? And what should this be incremented too?

The status message has it's own version number https://github.com/UKHomeOffice/design-system/blob/master/components/status-message/package.json

However, I notice all the components have the same version number. I'm not sure how significant your changes are (and whether they're breaking changes, minor changes or bug fixes) to know how much to increment the version number by. I also don't know if it's okay to increase the version number of one component and not the rest of the design system.

2022-12-16 11:19 UTC, daniel-ac-martin commented on pnpm-lock.yaml
> +lockfileVersion: 5.4
We've not changed the dependencies so this file shouldn't need to change and should be removed from the PR.

2022-12-16 11:20 UTC, daniel-ac-martin commented on components/status-message/assets/StatusMessage.scss
> +	@include govuk-responsive-padding(4, "all");
There are lots of stylistic changes, such as this white space change. This should be removed from the PR as it makes it hard to review what has actually changed.

2022-12-16 11:23 UTC, daniel-ac-martin requested changes
The preview looks good but there are some issues in the code that should be addressed.

2023-01-04 11:27 UTC, MikeDThorpe commented on components/status-message/assets/StatusMessage.scss
> +	@include govuk-responsive-padding(4, "all");
@daniel-ac-martin - this is from my local prettier settings which i can remove but not sure of the easiest way to revert them. Is there a formatting config file for the design system for contributors to use?

2023-01-05 10:50 UTC, MikeDThorpe commented
@daniel-ac-martin - could you please advise on the correct way to handle the conflict in the pnpm-lock.yml file?

2023-01-17 16:00 UTC, daniel-ac-martin commented on components/status-message/assets/StatusMessage.scss
> +	@include govuk-responsive-padding(4, "all");
>Is there a formatting config file for the design system for contributors to use?
Not currently. It's on my to-do list!

2023-01-17 16:02 UTC, daniel-ac-martin commented
@MikeDThorpe: As we aren't changing any dependencies, the file shouldn't need to change. So I'd suggest that we just take the pnpm-lock.yaml from the master branch and commit that on top of this branch.

2023-02-08 17:41 UTC, daniel-ac-martin requested changes
Sorry for the delay on reviewing this.

Just needs a few small changes, I think. Looks good otherwise.

2023-02-08 17:41 UTC, daniel-ac-martin commented on .jest-results.json
> +{"numFailedTestSuites":0,"numFailedTests":0,"numPassedTestSuites":13,"numPassedTests":115,"numPendingTestSuites":0,"numPendingTests":0,"numRuntimeErrorTestSuites":0,"numTodoTests":0,"numTotalTestSuit
Sorry can we remove this file from the PR. - It's a built file and we don't need to commit it.

(Sorry, I know I need to find a way to block this.)

2023-02-08 17:41 UTC, daniel-ac-martin commented on components/status-message/src/StatusMessage.tsx
> +        <p className={classes('status')}>{status}</p>
`{status}` isn't really a paragraph so I don't think we should use a `<p>` tag here.

I'd suggest we change this to a `<div>`.

2023-02-08 17:41 UTC, daniel-ac-martin commented on components/status-message/assets/StatusMessage.scss
> +  }
Extraneous white-space.

2023-02-16 16:28 UTC, tomyems approved these changes

2023-03-13 14:28 UTC, daniel-ac-martin approved these changes

2023-03-13 14:29 UTC, merged