495 new component highlight
UKHomeOffice/design-system pull request #498
Opened 2023-02-15 13:52 UTC by MikeDThorpe

- Scaffold files for new Highlight component
- Create component with html & styles as per guidance on ticket #495
- Add Storybook examples and component tests

2023-02-16 16:19 UTC, tomyems commented
We've got a slight design tweak to make. We discovered from our research, and you can see listed in the guidance, that the highlight works much better when bolded. In research we achieved this with `<strong>` tags, I guess you could also do this in css, but not sure which is better.

2023-02-16 16:28 UTC, tomyems commented
https://63ee57e933a4a934ea9e4755--hods.netlify.app/components?name=Highlight

2023-02-17 10:46 UTC, tomyems commented
With bold for the highlight: https://63ef54808b8cda566e2b42af--hods.netlify.app/components?name=Highlight

2023-02-27 13:13 UTC, tomyems commented
https://63fcabeb767019005583b658--hods.netlify.app/components?name=Highlight

2023-02-27 14:29 UTC, tomyems commented
https://63fcbae52b356b0d85c997c7--hods.netlify.app/components?name=Highlight

2023-03-02 12:36 UTC, daniel-ac-martin requested changes

2023-03-02 12:36 UTC, daniel-ac-martin commented on apps/docs/src/common/pages/patterns/compare-information.tsx
> +import { Highlight } from '../../../../../../components/highlight'
This should come out of the `@hods/components` package.

(And we will need to add this component to that package. - https://github.com/UKHomeOffice/design-system/blob/master/lib/components/src/index.ts )

2023-03-02 12:36 UTC, daniel-ac-martin commented on components/highlight/README.md
> +Hods - Highlight
Capitalise HODS.

2023-03-02 12:36 UTC, daniel-ac-martin commented on components/highlight/README.md
> +  />
Can we add an example here? (I usually take the first 'story' in the documentation.)

2023-03-02 12:36 UTC, daniel-ac-martin commented on components/highlight/assets/Highlight.scss
> +mark::after {
This will be applied to _all_ `<mark>`s. We _might_ want to do that but we should think carefully  about it.

I think for now we should just work off of `.hods_highlight`.

If memory serves, you should be able to use `&::before` and `&::after` within our `.hods_highlight` block above.

2023-03-02 12:36 UTC, daniel-ac-martin commented on components/highlight/src/Highlight.tsx
> +      <strong>
Should we use both `<mark>` and `<strong>`?

2023-03-02 14:53 UTC, MikeDThorpe commented on components/highlight/README.md
> +  />
Example added

2023-03-02 15:02 UTC, MikeDThorpe commented on components/highlight/src/Highlight.tsx
> +      <strong>
There's a comment on using `<mark>` and `<strong>` [ here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark). I think the recommendations are in line with how we use both in the component.

2023-03-02 15:03 UTC, MikeDThorpe commented on components/highlight/assets/Highlight.scss
> +mark::after {
I've refactored the css with the above suggestions.

2023-03-02 15:07 UTC, MikeDThorpe commented on apps/docs/src/common/pages/patterns/compare-information.tsx
> +import { Highlight } from '../../../../../../components/highlight'
@daniel-ac-martin  - like this? - `import { Highlight } from '@hods/components'`

2023-03-06 10:07 UTC, tomyems approved these changes
Content is good :)

2023-03-06 15:07 UTC, daniel-ac-martin commented on lib/components/src/index.ts
> +export { default as Highlight } from '@hods/Highlight';
`@hods/highlight` (lowercase)

This will need to be installed into the `lib/components` package, if it hasn't already.

```shell
$ cd lib/components/
$ pnpm i @hods/highlight
```

2023-03-06 15:10 UTC, daniel-ac-martin commented on apps/docs/src/common/pages/patterns/compare-information.tsx
> +import { Highlight } from '../../../../../../components/highlight'
Almost.

`@hods/highlight` (lowercase)

2023-03-07 15:36 UTC, tomyems commented
https://6407506a6a15180f524def75--hods.netlify.app/components?name=Highlight

2023-03-13 17:07 UTC, daniel-ac-martin approved these changes

2023-03-13 17:09 UTC, merged