494 new component loading spinner
UKHomeOffice/design-system pull request #500
Opened 2023-02-17 12:49 UTC by MikeDThorpe

- Scaffold files for new loading-spinner component
- Implement html and css styles as per desired code in the ticket
- Add test case

2023-02-20 09:03 UTC, tomyems commented
Looks good, thanks,

The style of the text underneath the loading spinner I think looks better like:

<img width="447" alt="image" src="https://user-images.githubusercontent.com/93599300/220060379-e1cee3f0-e389-4098-a40b-b3d6582f1cfd.png">

This is using the 'govuk-heading-m' class, is this possible?

2023-02-21 15:22 UTC, tomyems commented
> @tomyems - new commits for you to take a look at following your last comments regarding text styles. The example you gave looked to be a `p` tag or should the text content be wrapped in `h1`

It should be a `h1` as this is the content of primary importance on the page when it's loading. Looks good to me :)

Link: https://63f4d262acf7b52db2ea92dc--hods.netlify.app/components?name=Loading%20spinner

2023-02-27 13:09 UTC, tomyems commented
https://63fcab113b69be07fd6c00aa--hods.netlify.app/components?name=Loading%20spinner

2023-02-27 13:10 UTC, tomyems approved these changes
Approved. Content has been reviewed by a second person too. Ready for the working group on 2 March.

2023-03-02 12:51 UTC, daniel-ac-martin approved these changes

2023-03-02 12:51 UTC, daniel-ac-martin commented on components/loading-spinner/README.md
> +  />
Needs to have an example added.

2023-03-02 12:51 UTC, daniel-ac-martin commented on components/loading-spinner/README.md
> +Hods - Loading-Spinner
Capitalise HODS.

2023-03-02 12:51 UTC, daniel-ac-martin commented on components/loading-spinner/assets/LoadingSpinner.scss
> +}
Can you explain what's going on here? (Or send me some links?)

Am I write in assuming this is creating some sort of entity called 'spin' that can be referenced by other bit of CSS? If so, I think we should name it something less likely to clash; perhaps, 'hods-loading-spinner-animation'.

2023-03-02 12:51 UTC, daniel-ac-martin commented on components/loading-spinner/assets/LoadingSpinner.scss
> +    border-top-color: #005EA5;
Where do these colours come from? Are they part of any predefined palette that we can reference?

2023-03-02 12:51 UTC, daniel-ac-martin commented on components/loading-spinner/spec/LoadingSpinner.stories.mdx
> +    <LoadingSpinner textContent="Loading the next task for this case" />
Why not just take the text as children? i.e.
```jsx
<LoadingSpinner>Loading the next task for this case</LoadingSpinner>
```

2023-03-02 12:51 UTC, daniel-ac-martin commented on components/loading-spinner/spec/LoadingSpinner.stories.mdx
> +* Generic ID verification web
Let's use `-` rather than `*` to be consistent.

2023-03-02 12:51 UTC, daniel-ac-martin commented on components/loading-spinner/src/LoadingSpinner.tsx
> +        <h1 className='govuk-heading-m'>{textContent}</h1>
@tomyems: Given that we don't know where on the page this component will be used, are we certain that we should use an `<h1>`?

(An alternative approach would be to allow the user to provide any heading element that they might want. Although it's harder to enforce visual styling that way.)

2023-03-02 13:53 UTC, MikeDThorpe commented on components/loading-spinner/assets/LoadingSpinner.scss
> +}
Spin is a reference to an animation sequence - 0% being the start and 100% being the end. So if the animation lasts 2 seconds 0% will be the state of the component at 0s and 100% will be the state of the component after 2s. ([MDN Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations/Using_CSS_animations#defining_the_animation_sequence_using_keyframes))

i've renamed the animation name to "hods-loading-spinner-animation"

2023-03-02 13:56 UTC, MikeDThorpe commented on components/loading-spinner/README.md
> +  />
Following example added to component README:

`<LoadingSpinner textContent="Loading the next task in your case load" />`

2023-03-02 14:07 UTC, MikeDThorpe commented on components/loading-spinner/assets/LoadingSpinner.scss
> +    border-top-color: #005EA5;
@tomyems - can you answer this please? Can we add these colours to a HODS palette (or reference them from an existing one), especially if they are used, or are to be used, elsewhere.

2023-03-02 14:14 UTC, MikeDThorpe commented on components/loading-spinner/assets/LoadingSpinner.scss
> +    border-top-color: #005EA5;
Should we make `border-top-color: #005EA5` the same blue as used in all other components - i.e timeline border and status-message? Which is `#1d70b8`

2023-03-02 14:48 UTC, MikeDThorpe commented on components/loading-spinner/spec/LoadingSpinner.stories.mdx
> +    <LoadingSpinner textContent="Loading the next task for this case" />
To be honest it was just my default opinion for a smaller component to pass props. Happy to switch to passing children.

2023-03-03 08:37 UTC, tomyems commented on components/loading-spinner/src/LoadingSpinner.tsx
> +        <h1 className='govuk-heading-m'>{textContent}</h1>
The visual styling is provided by the className 'govuk-heading-m', rather than the semantic HTML `<h1>` tag. So `<h1 className='govuk-heading-m'>` is visually the same as `<h2 className='govuk-heading-m>`. What we have is fine if there's no other `<h1>` on the page.

Happy for the heading level to be customisable, but default to `h1`. If you think it would be easier, happy for the className to be customisable but default to `govuk-heading-m`.

2023-03-03 08:45 UTC, tomyems commented on components/loading-spinner/assets/LoadingSpinner.scss
> +    border-top-color: #005EA5;
Asked in the design discussion: https://github.com/UKHomeOffice/design-system/discussions/488#discussioncomment-5187760

I don't think the grey is defined anywhere, and I'd also be cautious about using it in another context, it could be easily misused. If it's better for you happy to add it to the palette, if we can add some guidance about when it's fine to use.

2023-03-06 10:03 UTC, tomyems commented on components/loading-spinner/assets/LoadingSpinner.scss
> +    border-top-color: #005EA5;
@MikeDThorpe yes happy to use the same blue as the timeline and status message :)

2023-03-06 14:19 UTC, MikeDThorpe commented on components/loading-spinner/assets/LoadingSpinner.scss
> +    border-top-color: #005EA5;
Change made to use `border-top-color: govuk-colour("blue")`

2023-03-06 14:30 UTC, daniel-ac-martin commented on components/loading-spinner/src/LoadingSpinner.tsx
> +        <h1 className='govuk-heading-m'>{textContent}</h1>
We discussed this briefly on the last call. It sounds like we should probably just stick with an H1 for now.

If we were to make it customisable, the interface would look something like:
```jsx
<LoadingSpinner>
  <h1>Loading...</h1>
</LoadingSpinner>
```

2023-03-06 14:31 UTC, daniel-ac-martin commented on components/loading-spinner/src/LoadingSpinner.tsx
> +  textContent,
Should this have a default? "Loading..."?

2023-03-07 14:32 UTC, MikeDThorpe commented on components/loading-spinner/src/LoadingSpinner.tsx
> +  textContent,
We could add default text or alternatively we could make the textContent optional - so we could have a spinner on its own or with text. @tomyems what would the research suggest on this?

2023-03-07 14:33 UTC, tomyems commented on components/loading-spinner/src/LoadingSpinner.tsx
> +  textContent,
It should have a default 'Loading page'

2023-03-09 16:17 UTC, MikeDThorpe commented on components/loading-spinner/src/LoadingSpinner.tsx
> +  textContent,
I've added a default "Loading..." text to the component - if you could please review and then we can possibly merge and close this.

2023-03-09 16:45 UTC, tomyems commented on components/loading-spinner/src/LoadingSpinner.tsx
> +  textContent,
Yes that looks good to me :)

2023-03-09 17:16 UTC, daniel-ac-martin commented on components/loading-spinner/spec/LoadingSpinner.stories.mdx
> +    <LoadingSpinner textContent="Loading the next task for this case" />
I think we should make this switch.

2023-03-09 17:17 UTC, daniel-ac-martin commented on components/loading-spinner/src/LoadingSpinner.tsx
> +  textContent: string
I think we should switch to children, but if we didn't this should be marked as optional.

2023-03-10 19:46 UTC, daniel-ac-martin commented on components/loading-spinner/src/LoadingSpinner.tsx
> +  children,
BTW, you could still use `= 'Loading...'` if you wanted.

2023-03-10 19:48 UTC, daniel-ac-martin requested changes
Looks good, but I've just noticed that the new component needs to be added to the `lib/components` package. (Like you did on #498.)

2023-03-17 14:34 UTC, MikeDThorpe commented on components/loading-spinner/src/LoadingSpinner.tsx
> +  children,
Changes pushed to use `children = 'Loading...'`

2023-03-17 19:11 UTC, daniel-ac-martin approved these changes
Nice work @MikeDThorpe. :-)

2023-03-17 19:11 UTC, merged